baseURL = "https://edithpuclla.com/"
title   = "Edith Puclla"
themes = ["papermod"]
languageCode = "en-us"

[taxonomies]
  category = "categories"

[params]
  description = "Developer • Speaker • Lifelong learner"
  ShowReadingTime = true
  defaultTheme = "auto"
  customCSS = ["css/custom.css"]
  canonifyURLs = true

[[menu.main]]
  name = "Home"
  url  = "/"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-home\"><path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"></path><polyline points=\"9 22 9 12 15 12 15 22\"></polyline></svg> "
  weight = 10
[[menu.main]]
  name = "Blog"
  url  = "/blog"
  weight = 20
  identifier = "blog"
[[menu.main]]
  name = "Developer"
  url  = "/categories/developer/"
  parent = "blog"
  weight = 10
[[menu.main]]
  name = "Outside Work"
  url  = "/categories/outside-work/"
  parent = "blog"
  weight = 20


[[menu.main]]
  name = "Music"
  url  = "/music"
  weight = 30
[[menu.main]]
  name = "Videos"
  url  = "/videos"
  weight = 40
[[menu.main]]
  name = "Graphics"
  url  = "/graphics"
  weight = 50
[[menu.main]]
  name = "Social"
  url  = "/social"
  weight = 60

[[menu.main]]
  name = "Favories"
  url  = "/categories/outside-work/sport/"
  weight = 70

[markup.goldmark.renderer]
  unsafe = true

[build]
  environment = "production"
  disableLiveReload = true

